[package]
name = "program3"
version = "0.1.0"
edition = "2021"

[dependencies]
vecshard = "0.2.1"
rand = "0.8.4"

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "benchmarks"
harness = false
